name: 'Setup uv'
description: 'Installs uv and syncs dependencies'

runs:
  using: 'composite'
  steps:
    - name: 'Install uv'
      uses: astral-sh/setup-uv@v5
      with:
        version: "latest"
    - name: 'Install dependencies'
      shell: bash
      run: uv sync --all-groups --frozen
