name: 'Setup Git'
description: 'Installs and configures Git'

inputs:
  safe-directory:
    description: 'Directory to mark as safe for Git operations'
    required: true
  ssh-key:
    description: 'SSH private key for Git operations'
    required: true

runs:
  using: 'composite'
  steps:
    - name: 'Setup SSH'
      shell: bash
      run: |
        mkdir -p ~/.ssh
        chmod 700 ~/.ssh

    - name: write-ssh-key
      shell: bash
      run: |
        install -m 600 -D /dev/null ~/.ssh/id_rsa
        echo "${{ inputs.ssh-key }}" > ~/.ssh/id_rsa
    - name: add-to-know-hosts
      shell: bash
      run: |
        host='github.com'
        echo "Adding keys for $host"
        # Create known_hosts file if it doesn't exist
        touch ~/.ssh/known_hosts
        chmod 600 ~/.ssh/known_hosts
        # Add GitHub's host key
        ssh-keyscan -H "$host" >> ~/.ssh/known_hosts
        echo "$host registered successfully"

    - name: 'Configure Git user'
      shell: bash
      run: |
        git config --global user.email "automator@arthur.ai"
        git config --global user.name "Arthur Automator"

    - name: 'Configure safe directory'
      shell: bash
      # run: git config --global --add safe.directory ${{ inputs.safe-directory }}
      # run: git config --global --add safe.directory ${{ runner.workspace }}
      run: git config --global --add safe.directory /__w/arthur-common/arthur-common

    - name: 'Fetch tags'
      shell: bash
      run: git fetch --tags origin || true

    - name: 'Show recent commits'
      shell: bash
      run: git log -n2

    - name: 'Show repository status'
      shell: bash
      run: git status
