name: 'Setup Git'
description: 'Installs and configures Git'

inputs:
  safe-directory:
    description: 'Directory to mark as safe for Git operations'
    required: true
  ssh-key:
    description: 'SSH private key for Git operations'
    required: true

runs:
  using: 'composite'
  steps:
    - name: write-ssh-key
      shell: bash
      run: |
        install -m 600 -D /dev/null ~/.ssh/id_rsa
        echo "${{ inputs.ssh-key }}" > ~/.ssh/id_rsa
    - name: add-to-know-hosts
      shell: bash
      run: |
        install -m 600 -D /dev/null ~/.ssh/known_hosts
        host='github.com'
        hosts="$(dig +short "$host" | grep -v '\.$' | sed -z 's|\n|,|g')$host"
        echo "Adding keys for $hosts"
        ssh-keyscan -H "$hosts" > ~/.ssh/known_hosts
        (ssh-keygen -F "$host" > /dev/null && echo "$host registered") \
          || echo "Failed to register $host"

    - name: 'Configure Git user'
      shell: bash
      run: |
        git config --global user.email "automator@arthur.ai"
        git config --global user.name "Arthur Automator"

    - name: 'Configure safe directory'
      shell: bash
      # run: git config --global --add safe.directory ${{ inputs.safe-directory }}
      # run: git config --global --add safe.directory ${{ runner.workspace }}
      run: git config --global --add safe.directory /__w/arthur-common/arthur-common

    - name: 'Fetch tags'
      shell: bash
      run: git fetch --tags origin || true

    - name: 'Show recent commits'
      shell: bash
      run: git log -n2

    - name: 'Show repository status'
      shell: bash
      run: git status
