name: Arthur Common CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-linter:
    if: |
      (!contains(github.event.head_commit.message, 'Bump version'))
    runs-on: ubuntu-latest
    container: python:3.12.9-bullseye
    env:
      SKIP: pytest-check,changelog-check
      GIT_DEPTH: 100
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: ${{ env.GIT_DEPTH }}
      - uses: ./.github/workflows/composite-actions/setup-git
        with:
          safe-directory: ${{ runner.workspace }}
      - uses: ./.github/workflows/composite-actions/setup-poetry
        with:
          poetry-version: 2.1.3
      - name: Run linters
        run: |
          poetry run autoflake src/
          poetry run isort src/
          poetry run black src/
          poetry run mypy --config-file pyproject.toml src/

  run-unit-tests:
    if: |
      (!contains(github.event.head_commit.message, 'Bump version'))
    runs-on: ubuntu-latest
    container: python:3.12.9-bullseye
    steps:
        - uses: actions/checkout@v4
        - uses: ./.github/workflows/composite-actions/setup-git
          with:
            safe-directory: ${{ runner.workspace }}
        - uses: ./.github/workflows/composite-actions/setup-poetry
          with:
            poetry-version: 2.1.3
        - name: Run unit tests
          shell: bash
          run: |
            set -o pipefail
            poetry run pytest tests/unit/ --cov --cov=src/arthur_common \
            --cov-report term \
            --junitxml=report.xml \
            | tee pytest-coverage.txt
        - name: Pytest coverage comment
          if: always()
          uses: MishaKav/pytest-coverage-comment@main
          with:
            pytest-coverage-path: pytest-coverage.txt
            junitxml-path: report.xml
            title: Coverage Report
        - name: Upload coverage report
          if: always()
          uses: actions/upload-artifact@v4
          with:
            name: test-results
            path: |
              report.xml
              pytest-coverage.txt
