name: Arthur Common Version Bump

on:
  push:
    branches:
      - main
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  bump-version:
    if: |
      (github.ref == 'refs/heads/main' && github.event_name == 'workflow_dispatch') ||
      (github.event_name == 'pull_request' && github.head_ref == 'zf/ssh-setup')
    runs-on: ubuntu-latest
    container: python:3.12.9-bullseye
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: ${{ env.GIT_DEPTH }}
      - uses: ./.github/workflows/composite-actions/setup-git
        with:
          safe-directory: ${{ runner.workspace }}
          ssh-key: ${{ secrets.AUTOMATOR_SSH_KEY }}
      # - uses: ./.github/workflows/composite-actions/setup-poetry
      #   with:
      #     poetry-version: 2.1.3
      # - name: Bump version
      #   if: github.event_name == 'workflow_dispatch'
      #   run: |
      #     pip install bump2version
      #     bump2version patch
      #     git push origin main
      #     git push --tags
      # - name: Test setup-git action
      #   if: github.event_name == 'pull_request'
      #   run: |
      #     echo "Testing setup-git action on PR"
      #     git status
      #     git log --oneline -5
