name: Arthur Common CI

on:
  push:
    branches:
      - main
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
  pull_request:
    branches:
      - main

jobs:
  run-linter:
    if: |
      (!contains(github.event.head_commit.message, 'Bump version')) &&
      (
        github.event_name == 'pull_request' ||
        (github.event_name == 'push' && !startsWith(github.ref, 'refs/tags/'))
      )
    runs-on: ubuntu-latest
    container: python:3.12.9-bullseye
    env:
      SKIP: pytest-check,changelog-check
      GIT_DEPTH: 100
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: ${{ env.GIT_DEPTH }}
      - uses: ./.github/workflows/composite-actions/setup-git
        with:
          safe-directory: ${{ runner.workspace }}
      - uses: ./.github/workflows/composite-actions/setup-poetry
        with:
          poetry-version: 2.1.3
      - name: Run pre-commit
        run: |
          CHANGED_FILES=$(git diff-tree --no-commit-id --name-only -r ${{ github.sha }})
          echo "$CHANGED_FILES" | xargs poetry run pre-commit run --color always --verbose --files

  run-unit-tests:
    if: |
      (!contains(github.event.head_commit.message, 'Bump version')) &&
      (
        github.event_name == 'pull_request' ||
        (github.event_name == 'push' && !startsWith(github.ref, 'refs/tags/'))
      )
    runs-on: ubuntu-latest
    container: python:3.12.9-bullseye
    steps:
        - uses: actions/checkout@v4
        - uses: ./.github/workflows/composite-actions/setup-git
          with:
            safe-directory: ${{ runner.workspace }}
        - uses: ./.github/workflows/composite-actions/setup-poetry
          with:
            poetry-version: 2.1.3
        - name: Run unit tests
          run: |
            poetry run pytest tests/unit/ --cov --cov=src/arthur_common --cov-report term --junitxml=report.xml | tee pytest-coverage.txt
        - name: Pytest coverage comment
          uses: MishaKav/pytest-coverage-comment@main
          with:
            pytest-coverage-path: pytest-coverage.txt
            junitxml-path: report.xml
            title: Coverage Report
        - name: Upload coverage report
          if: success()
          uses: actions/upload-artifact@v4
          with:
            name: test-results
            path: |
              report.xml
              pytest-coverage.txt
